### ISSUE TITLE
Should Falcon_Discover_Url be hard coded in src/function/register_new_account.py?

### ISSUE THREAD

**Issue by shawndwells** [CrowdStrike/Cloud-AWS#1]
From https://github.com/CrowdStrike/Cloud-AWS/blob/master/Control-Tower/src/function/register_new_account.py#L11:

`````logger = logging.getLogger()
logger.setLevel(logging.INFO)
Falcon_Discover_Url = 'https://ctstagingireland.s3-eu-west-1.amazonaws.com/crowdstrike_role_creation_ss.yaml'
`````

**Comment by jhseceng** [comment]
The stackset template requires a URL and now switched this to be regional.

**Comment by jhseceng** [comment]
Yes this URL is correct for now.   This template will be deprecated when the integration moves to AWS quickstarts.
