### ISSUE TITLE
Using the EKS implementation guide assumes EKS cluster was created

### ISSUE THREAD

**Issue by shawndwells** [CrowdStrike/Cloud-AWS#102]
![image](https://user-images.githubusercontent.com/5713754/136667141-7521a56d-4527-4af1-a343-6be9be298f6d.png)

current instructions assume EKS cluster was made during the implementation guide.

as a result the docs need to be updated to give instruction on how to pass through the kube config information

**Comment by redhatrises** [comment]
Closing this issue as we no longer support these tools from this repo.
