### ISSUE TITLE
409 account already exists

### ISSUE THREAD

**Issue by anurag1192** [CrowdStrike/Cloud-AWS#119]
https://github.com/CrowdStrike/Cloud-AWS/blob/master/Discover-for-Cloud-Templates/AWS/troubleshooting/scripts/

Running the above scripts is giving me the error - 409 account already exists. I can see in CS console that accounts are not yet registered. I created the roles using terraform. Obviously cannot share accountId's here, support told me create an issue here.

Any help appreciated. Thanks.

**Comment by jshcodes** [comment]
Ho @anurag1192!

A couple of troubleshooting questions:

- Has this account been registered in any other CIDs for Discover?
- If you run the script with the `-c` flag set to `delete` (it should remove this account) and then run it again using `-c` set to `register`, does it work?

**Comment by anurag1192** [comment]
Hi @jshcodes 
I found the mistake, I did register using console first that's why I was getting the error. Once I ran Delete and Register commands using provided scripts it worked.

Thanks
