### ISSUE TITLE
PowerShell Uninstall Script

### ISSUE THREAD

**Issue by jackmuskopf** [CrowdStrike/Cloud-AWS#143]
Hi,

On Windows, is it possible to uninstall the CrowdStrike sensor via a PowerShell script?  

I have only seen documentation that involves downloading a uninstall tool via the web UI; can this uninstall tool be downloaded via API call, such that the entire uninstall process can be done via a PowerShell script?

Thanks,
Jack

**Comment by bk-cs** [comment]
The uninstallation tool (`CsUninstallTool.exe`) is not required for uninstallation. Uninstallation can be scripted using the MSI-based uninstall features within Windows.

If your Sensor Update policy has Uninstall Protection enabled, you'll need to supply the appropriate uninstall token for the specific host during the uninstallation process.

[PSFalcon](https://github.com/crowdstrike/psfalcon) has a command called `Uninstall-FalconSensor` that is designed to use Real-time Response to trigger an MSI-based uninstall. If the host is within a Sensor Update policy that has uninstall protection enabled, the token will be included during the uninstall process.

**Comment by jackmuskopf** [comment]
Excellent, thank you for responding.  We will look into these options!
