### ISSUE TITLE
option-b---creating-a-package-without-the-installer

### ISSUE THREAD

**Issue by jrv912** [CrowdStrike/Cloud-AWS#144]
This step references a .zip file that we need to unzip locally before running the packager.py script (package-without-binary.zip).  

where is this .zip file located?  I can't locate it in the repo - do we create it manually?

https://github.com/CrowdStrike/Cloud-AWS/blob/main/systems-manager/documentation/AWS-Systems-Manager-Intro.md#option-b---creating-a-package-without-the-installer

**Comment by jrv912** [comment]
IT appears these zi

<html>
<body>


Two zip files are included in the *Packaging-utilities/zip-files* folder that contain example files for creating a
--
208 | CrowdStrike package for AWS Systems Manager.


</body>
</html>p files were removed?

**Comment by jrv912** [comment]
Thank you!

**Comment by jshcodes** [comment]
Hi @RuBiCK!

We have an example that contains the contents of this legacy archive located here: https://github.com/CrowdStrike/Cloud-AWS/tree/main/state-manager/ssm-distributor 

This solution also contains an enhancement that demonstrates downloading the sensor from the API, bundling it into the distributor package, and then deploying it to S3. (e.g. The sensor is downloaded at package creation, not during sensor deployment.)

Let us know if there are any questions.

**Comment by RuBiCK** [comment]
Thanks for the information @jshcodes!

I'm facing different errors and following the documentation. In S3 bucket it sucessfully create and upload files to `falcon/` but doesn't appear the files in the root folder like `layer.zip`, `createSsmParams.zip`, `lamda_ssm_setup.zip` and `Local-CrowdStrike-Automation-Doc.yml`

I'm going to upload them manually and keep with the installation instructions

**Comment by jshcodes** [comment]
Uploading them to the bucket should work.  You don't need to upload the YAML file. (`CrowdStrike-Automation-Doc.yml`)
