### ISSUE TITLE
StackSet CrowdstrikeDiscover-IAM-ROLES not found

### ISSUE THREAD

**Issue by ichikata** [CrowdStrike/Cloud-AWS#159]
Hi 👋 , I'm trying to deploy [AWS Control Tower with CrowdStrike Discover for Cloud and Containers](https://github.com/CrowdStrike/Cloud-AWS/blob/main/Control-Tower/README.md) for automatically enrolling new accounts to Crowdstrike Discover, provisioned with Account Factory via Control Tower.

So far I've successfully executed both CloudFormation templates in the log-archive and master accounts (all of the expected resources were created, some with different naming that the ones described in the [Implementation Guide](https://github.com/CrowdStrike/Cloud-AWS/blob/main/Control-Tower/documentation/implementation-guide.md) ).

Once I proceed to create a new account, I expected the newly provisioned account to have the CrowdStrike resources created (IAM Role, Lambda Function) but they're missing. In the master account logs, the only error i'm getting is the following:

```
[ERROR] Unable to launch in:CrowdstrikeDiscover-IAM-ROLES, REASON: An error occurred (StackSetNotFoundException) when calling the CreateStackInstances operation: StackSet CrowdstrikeDiscover-IAM-ROLES not found
```

Do you have any recommendations on how to proceed? Thanks in advance

**Comment by jhseceng** [comment]
Thank you for reporting the issue.  We will investigate
