### ISSUE TITLE
Control-Tower-For-Horizon - Access Denied by S3

### ISSUE THREAD

**Issue by ichikata** [CrowdStrike/Cloud-AWS#160]
Hi there 👋 , I've followed the documentation for enabling AWS Control Tower for Horizon as described [here](https://github.com/CrowdStrike/Cloud-AWS/blob/main/Control-Tower-For-Horizon/documentation/implementation-guide.md), and I run into the following error while running the CloudFormation [template](https://github.com/CrowdStrike/Cloud-AWS/blob/main/Control-Tower-For-Horizon/cloudformation/Falcon_Horizon_Control_Tower.yaml):

`
"Your access has been denied by S3, please make sure your request credentials have permission to GetObject for crowdstrike-sa-resources-ct-us-east-2/push_horizon_stackset_lambda.zip. S3 Error Code: AccessDenied. S3 Error Message: Access Denied (Service: Lambda, Status Code: 403, Request ID: 29776818-1202-402a-a58e-11f677d85569)" (RequestToken: b9e84743-624c-1c79-7c24-a53c9b9a9924, HandlerErrorCode: AccessDenied)
`

I fulfilled all of the prerequisites, and as for the API scopes, I enabled r/w permissions to`AWS accounts, CSPM registration, CSPM remediation, Detections, Device control policies, Hosts, Falcon Discover, Host groups, Incidents, Installation Tokens, IOC Manager APIs and Event streams`

The AWS region of the account is `us-east-2`, and the crowdstrike api is `us1` ( https://api.crowdstrike.com )

Is there anything I'm missing? Thanks in advance

**Comment by redhatrises** [comment]
Control Tower now uses AWS built-in. For questions and issues, please go to https://github.com/aws-ia/cfn-abi-crowdstrike-fcs
