### ISSUE TITLE
[HELP] Falcon Node Sensor Deployment Faiilure

### ISSUE THREAD

**Issue by dempti** [CrowdStrike/Cloud-AWS#162]
Hi Team,

I was following a guide as per the [documentation](https://github.com/CrowdStrike/Cloud-AWS/blob/main/Container%20Security/kernel-eks-implementation-guide.md)

The deployment completes succeessfully, however there are few issues which needs help fixing.

When trying to verify if the node sensor is fully up to verify if `Falcon Sensor for Linux has insert itself to the kernel` , logs on falcon node sensor looks like this
```
❯ k logs --tail 100 -f -n falcon-system falcon-helm-falcon-sensor-24xzr

Defaulted container "falcon-node-sensor" out of: falcon-node-sensor, init-falconstore (init)
Mon May 23 05:42:26 2022 Invalid file /opt/CrowdStrike/falconstore length: 0    (27756) [624]

```

Also verifying from inside the pods
```
❯ k exec -n falcon-system falcon-helm-falcon-sensor-24xzr --stdin --tty -- /bin/sh

Defaulted container "falcon-node-sensor" out of: falcon-node-sensor, init-falconstore (init)

sh-4.2#
sh-4.2# lsmod|grep falcon
sh-4.2# exit
```

Environment Information
```
eks -> 1.22
node type -> t3.xlarge
```

**Further Query:**
Do we also require to installl falcon-sensor if we have deployed falcon-node-sensor?

**Comment by isimluk** [comment]
Thank You @dempti for letting us know about the issue. We have been able to reproduce this internally.

**Comment by isimluk** [comment]
I cannot reproduce this issue with falcon-operator it seems to be isolated to falcon-helm only. /cc @domdepasquale

----

@dempti, we are looking into the issue of falcon-helm. In the mean-time, if you want to proceed with alternative installation method, you can use https://github.com/crowdstrike/falcon-operator now. 

Helm and Operators are alternative installation / delivery methods to kubernetes. It is up to you to decide which one is right fit for your particular environment.

Here are the steps to proceed with the operator, as an interim before the helm option gets fixed.

 - uninstall helm: helm uninstall falcon-helm -n falcon-system
 - install operator: kubectl apply -f https://raw.githubusercontent.com/CrowdStrike/falcon-operator/main/deploy/falcon-operator.yaml
 - install the node sensor: kubectl create -f https://raw.githubusercontent.com/CrowdStrike/falcon-operator/main/config/samples/falcon_v1alpha1_falconnodesensor.yaml --edit=true

You may want to read through the operator documentation before you proceed: https://github.com/CrowdStrike/falcon-operator/tree/main/docs/node

**Comment by domdepasquale** [comment]
I tested with helm chart version 1.17.0, falcon image tag `6.39.0-13601.falcon-linux.x86_64.Release.US-1`, and EKS version 1.20, 1.21, & 1.22. Everything worked as expected for the node install.

```
╰─❯ kg nodes
NAME                           STATUS   ROLES    AGE   VERSION
ip-10-10-119-35.ec2.internal   Ready    <none>   34m   v1.22.6-eks-7d68063
ip-10-10-121-72.ec2.internal   Ready    <none>   34m   v1.22.6-eks-7d68063
```

```
╰─❯ kgpo -owide -n falcon-system
NAME                              READY   STATUS    RESTARTS   AGE   IP             NODE                           NOMINATED NODE   READINESS GATES
falcon-helm-falcon-sensor-8dpv2   1/1     Running   0          65s   10.10.121.72   ip-10-10-121-72.ec2.internal   <none>           <none>
falcon-helm-falcon-sensor-dm4hh   1/1     Running   0          65s   10.10.119.35   ip-10-10-119-35.ec2.internal   <none>           <none>
```

```
╰─❯ klo -n falcon-system falcon-helm-falcon-sensor-8dpv2 --tail 100
Thu May 26 15:24:10 2022 Invalid file /opt/CrowdStrike/falconstore length: 0	(25152) [624]
```

_Note: that "Invalid file" message is just a warning and is expected on new installs_

```
╰─❯ kex -n falcon-system falcon-helm-falcon-sensor-dm4hh --stdin  --tty -- /bin/sh
Defaulted container "falcon-node-sensor" out of: falcon-node-sensor, init-falconstore (init)
sh-4.2# lsmod | grep falcon | wc -l
4
sh-4.2# exit
```

**Comment by dempti** [comment]
@domdepasquale if that is the case why is this `sh-4.2# lsmod|grep falcon` not showing any output could you help me out here.
don't seem the falcon sensor has inserted itself.

**Comment by redhatrises** [comment]
> @domdepasquale if that is the case why is this `sh-4.2# lsmod|grep falcon` not showing any output could you help me out here. don't seem the falcon sensor has inserted itself.
> 
> @isimluk just did the installation of Node Sensor using helm and now I can see falcon sensor has inserted itself.
> 
> Also, could you help me understand the
> 
> 1. Differences between `Falcon Node Sensor` and `Falcon Container Sensor`.

The Falcon Node sensor is meant for installation on kubernetes control-plane and worker nodes when/if you have access to those nodes. The Falcon Container sensor is a sidecar container sensor that is meant for certain managed kubernetes environments where you do not have node access... for example, EKS fargate.

> 2. Should both of these need to be installed at once?

They should not be installed at once.

Do these answers make sense?

**Comment by redhatrises** [comment]
Closing as there is no further movement on this. Please reopen if necessary.
