### ISSUE TITLE
How to provide crowdstrike security for EC2 instances running in private and data Subnet , where internet is disabled

### ISSUE THREAD

**Issue by rahul9913102258** [CrowdStrike/Cloud-AWS#170]

**Comment by TomRyan-321** [comment]
Hi @rahul9913102258 
Connectivity to Crowdstrike for instances running in subnets without internet access can be achieved via AWS privatelink. See the resources in the following link: https://github.com/CrowdStrike/Cloud-AWS/tree/main/aws-privatelink

Do note we only host endpoints in the same regions where the falcon service itself is hosted for each falcon region. You will need to leverage transit gateway to enable cross region routing if your workloads are not in the same region as our service.

Falcon us-1 == AWS us-west-1
Falcon us-2 == AWS us-west-2
Falcon eu-1 == AWS eu-central-1

**Comment by musayev-io** [comment]
I am closing this as @TomRyan-321's response is the correct guidance to provide connectivity back to the CrowdStrike clouds for workloads without internet connectivity.

**Comment by rahul9913102258** [comment]
Thank You !
