### ISSUE TITLE
Do we have these templates for the gov environment?

### ISSUE THREAD

**Issue by Pradipna** [CrowdStrike/Cloud-AWS#176]
Hi , I am trying to automate the deployment of Crowdstrike in our AWS infrastructure, While going through the template I see that the CrowdStrike cloud listed does not have Gov cloud. CrowdStrikeCloud: Default: us1 Description: The CrowdStrike Cloud your CID is hosted in us1, us2, eu Type: String AllowedValues: - us1 - us2 - eu Is it supported? 

I think it would be great for the Gov cloud users to have these templates available for them as well.

https://github.com/CrowdStrike/Cloud-AWS/tree/main/Control-Tower/log-archive-acct 

Thank you.

Regards,
Pradipna Gautam

**Comment by redhatrises** [comment]
Control Tower is now a part of AWS Builtin... For issues and questions, please see https://github.com/aws-ia/cfn-abi-crowdstrike-fcs
