### ISSUE TITLE
Query on AWS Install to Amazon Linux 2

### ISSUE THREAD

**Issue by StephenGoodall** [CrowdStrike/Cloud-AWS#184]
Hi,
I've been trying to get this setup recently (https://github.com/CrowdStrike/Cloud-AWS/tree/main/state-manager) and I'm seeing the following error in the runCommand logs:
```
uninstall errors: sudo: /opt/CrowdStrike/falconctl: command not found
No Match for argument: falcon-sensor

install errors: Warning: RPMDB altered outside of yum.
warning: falcon-sensor.rpm: Header V4 RSA/SHA512 Signature, key ID 519b177f: NOKEY
error: Failed dependencies:
	ld-linux-aarch64.so.1()(64bit) is needed by falcon-sensor-6.41.0-13804.amzn2.aarch64
	ld-linux-aarch64.so.1(GLIBC_2.17)(64bit) is needed by falcon-sensor-6.41.0-13804.amzn2.aarch64
	libdl.so.2(GLIBC_2.17)(64bit) is needed by falcon-sensor-6.41.0-13804.amzn2.aarch64
	libm.so.6(GLIBC_2.17)(64bit) is needed by falcon-sensor-6.41.0-13804.amzn2.aarch64
	libpthread.so.0(GLIBC_2.17)(64bit) is needed by falcon-sensor-6.41.0-13804.amzn2.aarch64
install.sh: line 11: /opt/CrowdStrike/falconctl: No such file or directory
Failed to restart falcon-sensor.service: Unit not found.
```

I think the uninstall error is OK as it won't have been installed at that point, but the dependencies errors seem to be the cause of the issues for me. Later attempts return with a response saying the Document has already been installed so it just says that every 30 minutes due to the schedule.

Does the falcon sensor 6.41.0 need something that is not included in the amzn2-ami-kernel-5.10-hvm-2.0.20220606.1-x86_64-gp2 AMI? (I also just tested on amzn2-ami-hvm-2.0.20220719.0-x86_64-gp2 which is kernel 4.14 and saw the same output)

(This is the first time i've used AWS Systems manager etc. so apologies if some of the above is basic - let me know if i need to provide more info 🙄 )

Thanks

**Comment by StephenGoodall** [comment]
I'm not sure why it thinks the sensor is installed (at a guess, SSM didn't see any errors on the first run so it thinks it's OK?) but this might be something extra to consider?
https://github.com/aws/amazon-ssm-agent/issues/366

Or, if that validate.sh is not officially supported then could some validation maybe be added to the install.sh script?

**Comment by redhatrises** [comment]
Hello,

This is most likely due to the `install.sh` script using the `rpm` command instead of the `yum` command to install the sensor. The install is erroring because the dependencies the sensor needs are not installed. Switching from `rpm` to `yum` should fix the install problem.

**Comment by StephenGoodall** [comment]
Thanks @redhatrises I updated the install.sh to the following:
```
#!/bin/bash
#
# Distributor package installer - Amazon Linux 2 / RPM based distros
#
filename="falcon-sensor.rpm"

rpmInstall() {
  yum install libnl -y
  yum install -y -v "$1"
  echo "/opt/CrowdStrike/falconctl -s -f --cid=$2" >>log.txt
  /opt/CrowdStrike/falconctl -s -f --cid="$2" $3
  systemctl restart falcon-sensor
  rm $1
}

rpmInstall $filename $SSM_CS_CCID $SSM_CS_INSTALLPARAMS
```

But now I get this error:
```
Cannot add package falcon-sensor.rpm to transaction. Not a compatible architecture: aarch64
```

The instance and AMI is x86_64:
```
sh-4.2$ uname -a
Linux ip-xxx-xx-xx-xxx.ap-southeast-2.compute.internal 4.14.287-215.504.amzn2.x86_64 #1 SMP Wed Jul 13 21:34:43 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```


I think the download.py might be getting the first one in the list, which is an arm64 version, when really I would need the second one:
```
			{
				"name": "falcon-sensor-6.41.0-13804.amzn2.aarch64.rpm",
				"description": "Falcon Kernel sensor for Amazon Linux 2",
				"platform": "linux",
				"os": "Amazon Linux",
				"os_version": "2 - arm64",
				"sha256": "ea1f98633eb20c17d7be671298ca05a7c84a94026ff29c7d60c35d7f5dbb2b3a",
				"release_date": "2022-07-12T22:18:08.169Z",
				"version": "6.41.13804",
				"file_size": 5231704,
				"file_type": "rpm"
			},
			{
				"name": "falcon-sensor-6.41.0-13804.amzn2.x86_64.rpm",
				"description": "Falcon Kernel Sensor for AMI/Amazon",
				"platform": "linux",
				"os": "Amazon Linux",
				"os_version": "2",
				"sha256": "5f4ec38497097a5d42ea3e6d3a66fda493620ce2ea726481688e6bd6ffb4c1da",
				"release_date": "2022-07-12T22:13:12.438Z",
				"version": "6.41.13804",
				"file_size": 27878828,
				"file_type": "rpm"
			},
```

Does the create package.sh script maybe need something adding to pass on the os_version as the -v parameter?


I tested changing it to this:
```
python download.py -k $1 -s $2 -d -o amzn -v "2" -n CS_AMAZON2_x86_64/falcon-sensor.rpm
```

And it seems to have pulled the second sensor down now so I'll test that out with SSM today. If that works then should I look at a way to parse the agent_list file and pass that through, then raise a PR in the repo where that script is saved?

**Comment by StephenGoodall** [comment]
https://github.com/CrowdStrike/Cloud-AWS/pull/185
