### ISSUE TITLE
Error when trying to use the standard download script

### ISSUE THREAD

**Issue by mobious999** [CrowdStrike/Cloud-AWS#189]
When trying to use the packager to create the distribution package the cached property import fails.

Traceback (most recent call last):
  File "packager.py", line 14, in <module>
    from functools import cached_property
ImportError: cannot import name 'cached_property'

**Comment by musayev-io** [comment]
This is likely because you're running a version of Python < 3.8, as that's when `cached_property` was introduced. If upgrading Python is not an option, feel free to omit the import statement and the `@cached_property` decorators. Everything should work fine!
