### ISSUE TITLE
Allow using named Aws profiles for the agents

### ISSUE THREAD

**Issue by mobious999** [CrowdStrike/Cloud-AWS#190]
The script assumes you have one set of credentials setup.

When you have multiple accounts you use named profile to run all aws commands aws s3 ls --profile xxxxx.

Add the option to allow using profiles in the scripts

**Comment by TomRyan-321** [comment]
Hey @mobious999 which script are you referring to, there are a number in these repo.

Also one thing you could try is passing through profile to the script as follows
`env AWS_PROFILE=<profilename> ./script.sh`

Alternatively export it as the active profile as so:
`export AWS_PROFILE=<profilename>`

**Comment by mobious999** [comment]
I was just following along with the repo directions.

I wanted to try the default w/o any customization.

The two statements assume that I'm deploying from mac or linux (I'm on windows).

**Comment by TomRyan-321** [comment]
We can look at adding some notes around profile usage, in terms of windows lots of the customers we work with typically have access to a *nix shell of some sorts (WSL2, CloudShell etc). In terms of direct Windows usage, would you be expecting Powershell based scripts?

**Comment by redhatrises** [comment]
Thanks for opening this issue. We now recommend the use of AWS SSM Distributor to handle automatically installing the agents in AWS cloud accounts.
