### ISSUE TITLE
Chores: broken links in the docs

### ISSUE THREAD

**Issue by isimluk** [CrowdStrike/Cloud-AWS#191]
It has brought to my attention that this repo contains broken links. This is a tracking issue for me to programatically detect and then fix various broken links in our publicly facing docs.

**Comment by redhatrises** [comment]
Thanks for opening this and implementing the programmtic methods for detecting broken urls. Closing this issue as part of cleaning up the open issues and probably doesn't make sense to keep this open anymore. Thanks!
