### ISSUE TITLE
ZIP files folder referenced in documentation does not exist

### ISSUE THREAD

**Issue by slowry-lo3** [CrowdStrike/Cloud-AWS#214]
The _Packaging-utilities/zip-files_ folder referenced here [Step 1 - Create your AWS SSM package](https://github.com/CrowdStrike/Cloud-AWS/blob/main/systems-manager/documentation/AWS-Systems-Manager-Intro.md#step-1---create-your-aws-ssm-package) does not exist.

**Comment by ffalor** [comment]
Hello, @slowry-lo3 I am looking into this

**Comment by ffalor** [comment]
It looks like the doc wasn't updated when those zip files were removed. You no longer need to unzip a zip file instead the zip file content was committed to the examples folder.

<img width="252" alt="image" src="https://user-images.githubusercontent.com/35144141/218171841-a60059ea-ef9a-4ce1-9c1f-424ca135edd4.png">

**Comment by ffalor** [comment]
We are revamping and cleaning up this repository. As part of that effort our ssm examples have been move to [aws-ssm-distributor](https://github.com/CrowdStrike/aws-ssm-distributor)

These new examples resolve the issues currently present in the `systems-manager` folder.
