### ISSUE TITLE
Package is not supported (package is missing install action)

### ISSUE THREAD

**Issue by Tan-tan-san** [CrowdStrike/Cloud-AWS#221]
I’ve created an SSM automation deployment successfully using option B in the README. The execution works until the last step which is the installation task. Im testing with two instance types: Amazonlinux2 and Windows 2019 server. Both deployed as EC2 instances using AWS’s AMI’s. SSM was confirmed functional on both as well. The Linux instance works flawlessly, while the windows part fails with:                       
`Package is not supported (package is missing install action)`

Things I have tried so far:
Repackaging the installer using the packager.py with the various versions I’ve found in this repo for the windows install.ps1/uninstall.ps1 scripts.

Downloaded the files I have uploaded to S3 and confirmed their checksum matched the included manifest.json. 

I’m at a loss at this point as to why its failing to find the package while the Linux install in the same document works.

**Comment by ffalor** [comment]
For the people who may come across this issue:

We are revamping and cleaning up this repository. As part of that effort our ssm examples have been move to [aws-ssm-distributor](https://github.com/CrowdStrike/aws-ssm-distributor)

These new examples resolve the issues currently present in the `systems-manager` folder.
