### ISSUE TITLE
What to put in the "Key" value when trying to run Cloudformation based security-hub integration?

### ISSUE THREAD

**Issue by steven-tan** [CrowdStrike/Cloud-AWS#241]
Hi, I'm trying to run a CloudFormation job using Security-Hub/cloudformation/security-hub-integration.yaml - but I can't figure out what to use for the "Key" value. The text description just says "The key used to access the instance." - and the documentation states this is an SSH key.

I tried generating a public RSA key, but when I paste the key into that field while trying to run a Cloudformation stack, the process eventually bombs out and says "Value for parameter <public rsa key here> is invalid. Length exceeds maximum of 255. (Service: AmazonEC2; Status Code: 400"

Standard rsa key seems to be over 700 characters long.

What exactly am I supposed to be pasting in that field?

**Comment by jshcodes** [comment]
Hi @steven-tan -

This should be the name of the EC2 key pair used to access the instance in AWS.   This does mean the key needs to pre-exist in your AWS environment before running the deployment script.

**Comment by steven-tan** [comment]
That did the trick, thanks so much @jshcodes !
