### ISSUE TITLE
Incorrect API permissions described

### ISSUE THREAD

**Issue by Gabriel-Stoba** [CrowdStrike/Cloud-AWS#266]
Hey team, the guide states only the  'sensor download' permissions is needed for the CrowdStrike API but misses 'Falcon Images Download' causing an error.

**Comment by musayev-io** [comment]
Hey Gabriel, can you please provide a link to the integration you're referring to? Thanks!

**Comment by Gabriel-Stoba** [comment]
Hey, @musayev-io, apologies! I was referring to the deployment guide for EKS Fargate https://github.com/CrowdStrike/Cloud-AWS/blob/main/container/eks-implementation-guide.md

**Comment by redhatrises** [comment]
Closing as this guide is no longer maintained in this repo.
