### ISSUE TITLE
No linux/arm64 tooling container available for the EKS guide

### ISSUE THREAD

**Issue by JamesLochheadCRWD** [CrowdStrike/Cloud-AWS#272]
The EKS guide here points to downloading a tooling container: 

https://github.com/CrowdStrike/Cloud-AWS/blob/65ba8bf488133f1fa3a45b1ac6697c60f928a6df/container/kernel-eks-implementation-guide.md?plain=1#L39

The tooling container does not have a Linux ARM64 build and therefore this command will fail on an Apple silicon Mac, giving this error:

```
docker: image with reference quay.io/crowdstrike/cloud-tools-image:latest was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64.
```

**Comment by carlosmmatos** [comment]
Thanks for opening this up. We will look into this as I think there is an existing issue requesting multi-arch support in that project.

**Comment by redhatrises** [comment]
Closing this issue as we no longer support these tools from this repo.
