### ISSUE TITLE
falcon-node-sensor-push context in the EKS docs

### ISSUE THREAD

**Issue by JamesLochheadCRWD** [CrowdStrike/Cloud-AWS#273]
https://github.com/CrowdStrike/Cloud-AWS/blob/65ba8bf488133f1fa3a45b1ac6697c60f928a6df/container/kernel-eks-implementation-guide.md?plain=1#L138

In the EKS docs, there is mention of a `falcon-node-sensor-push` script but no context about where you get it.

This may relate to as it may come as part of that container image.

**Comment by carlosmmatos** [comment]
that's correct, it is part of the container image:
https://github.com/CrowdStrike/cloud-tools-image

**Comment by redhatrises** [comment]
Closing this issue as we no longer support these tools from this repo. Either Skopeo should be used directly or the container script from github.com/crowdstrike/falcon-scripts should be used.
