### ISSUE TITLE
Findings Not Populating in Security Hub After CrowdStrike Subscription ([security-hub-integration.yaml])

### ISSUE THREAD

**Issue by AditModi** [CrowdStrike/Cloud-AWS#280]
I successfully deployed the CloudFormation template for the CrowdStrike integration with Security Hub [link](https://github.com/CrowdStrike/Cloud-AWS/tree/main/Security-Hub/cloudformation). However, even after subscribing to CrowdStrike findings in the deployed region, I am not seeing any findings populate within Security Hub.

Steps to Reproduce:

- Deployed the CloudFormation template with necessary parameters.
- Successfully launched the stack.
- Subscribed to CrowdStrike findings in the deployed region ([us-east-1]).
- Verified Security Hub for findings, but none are present.

Expected Behavior:

- After deployment and subscription, Security Hub should begin receiving and displaying findings from CrowdStrike.

Actual Behavior:

- No CrowdStrike findings are populating in Security Hub.

Possible Causes:

- Issue with Lambda function processing detections and submitting findings to Security Hub.
- Misconfiguration during subscription process within CrowdStrike.

**Comment by AditModi** [comment]
I did little bit of debugging in my EC2 and found that I get following error messages from fig_service.log:

`Configuration parameters loaded from SSM Parameter Store
No Streams available
Process terminated
Specified configuration file not found
`

**Comment by carlosmmatos** [comment]
@AditModi Let's start with verifying SSM:
https://github.com/CrowdStrike/Cloud-AWS/blob/main/Security-Hub/README.md#using-aws-systems-manager-parameter-store

Make sure you have those set

**Comment by AditModi** [comment]
Hi @carlosmmatos ,
thanks for the help. I added the debugging step and checked again. 
I found that the appID was the issue, it was giving the 400 error. I made changes to it and Now, I have it working as expected.

I get following messages from fig_service.log:

```
Configuration parameters loaded from SSM Parameter Store.
Starting listener on partition number 0...
All threads started, main process sleeping.
Process terminated
```

I am still not able to view the crowdstrike related information in security hub.

**Comment by carlosmmatos** [comment]
At this point you need to review/test detections. Per the docs:

`{app_id}_{partition_number}.log` - Each stream opened by the application has it's own rotating log that contains details regarding the detections discovered. Review this log to confirm detections are being discovered within the event stream and are properly formatted / meeting severity threshold requirements. This file is named after the value used for the __*app_id*__ parameter and the partition number.

This log file will tell you if anything has been processed.

**Comment by AditModi** [comment]
Thanks for the explanation on reviewing the CrowdStrike logs. I've checked the  {app_id}_{partition_number}.log files, and there are no detections found.

Based on this, it seems the issue likely lies with CrowdStrike sensor configuration.  On the AWS side, I've created and added the client ID and secret for the CrowdStrike Falcon Integration Gateway (FIG).

Could you please clarify if there are any other configuration steps required on the CrowdStrike side beyond the client credentials?

**Comment by carlosmmatos** [comment]
Are there any detections at all in your CID? You can check on the console. Outside of that, it sounds like you have configured everything you need on your end. 

My suggestions:
- Get with somebody who can run a test detection on a system that has the falcon-sensor installed.
  - Make sure this detection meets your defined severity threshold (`severity_threshold` or `FIG_SEVERITY_THRESHOLD`) otherwise you won't see it processed by the FIG.
- Verify the detection shows on the console
- Check the logs again

**Comment by redhatrises** [comment]
Closing as their is no further movement. Please re-open if necessary.
