### ISSUE TITLE
Dead links in Network Firewall Templates

### ISSUE THREAD

**Issue by shawndwells** [CrowdStrike/Cloud-AWS#37]
https://github.com/CrowdStrike/Cloud-AWS/tree/master/Network%20Firewall%20Templates links to https://github.com/CrowdStrike/Cloud-AWS/blob/master/Network%20Firewall%20Templates/cloudformation/add_crwd_to_existing_fw.yaml, which does not exist

**Comment by shawndwells** [comment]
@jhseceng bump

**Comment by jhseceng** [comment]
Jira Ref SOLAR-559

**Comment by jhseceng** [comment]
Removing the file for now.   Will evaluate if this is still required based on demand
