### ISSUE TITLE
Duplicate resource names in the D4C (AWS) Terraform template

### ISSUE THREAD

**Issue by Karmali** [CrowdStrike/Cloud-AWS#55]
Hi, 
Relaying a customer-reported issue in https://github.com/CrowdStrike/Cloud-AWS/blob/master/Discover-for-Cloud-Templates/AWS/terraform-templates/additional-account-existing-trail/falcon_discover_access.tf

> The resources on lines 1 & 55 have the same name. This name is also used elsewhere in the template. Can you have your team review the repo and update it to fix the bug?

**Comment by shawndwells** [comment]
@jhseceng bump

**Comment by jhseceng** [comment]
Thank you for the feedback.   We have identified the problem and expect to have a fix by 26/3/2021

**Comment by jshcodes** [comment]
These templates have been updated.  Let us know if you have any more questions or encounter any other issues.  :smile:
