### ISSUE TITLE
Terraform links in Readme.md for Discover seem to be dead

### ISSUE THREAD

**Issue by xcoldfyrex** [CrowdStrike/Cloud-AWS#58]
The following links are a 404: 
- Terraform templates for the log archive account creating new bucket
- Terraform templates for the log archive account using an existing bucket
- Terraform templates for additional accounts creating new CloudTrail log
- Terraform templates for additional accounts using and existing CloudTrail log

**Comment by jshcodes** [comment]
These links have been updated.
