### ISSUE TITLE
Discover Control Tower deployment does not seem to be picking up environment modifications

### ISSUE THREAD

**Issue by syn7ack** [CrowdStrike/Cloud-AWS#80]
Followed the deployment guide for Falcon Discover with Control Tower (https://github.com/CrowdStrike/Cloud-AWS/blob/master/Control-Tower/README.md).  CloudFormation run in Master Account and LogArchive account, then StackSet manually pushed to existing accounts.

Accounts were registered in API...EC2, EBS, and VPC data picked up and reported after registration...but then subsequent changes (i.e. termination of a test EC2 instance) were never reflected in the CrowdStrike console (been approximately 5 days now).

Assistance would be appreciated.  Please let me know what other information would help.  Thank you!

**Comment by shawndwells** [comment]
Thanks for reporting this @syn7ack!

Bump to @jhseceng , who authored much of this code.

**Comment by jhseceng** [comment]
Hello.   From your description it sounds like the configuration of the log archive account is somehow incorrect.   If you are seeing instances ok that would imply that the stacksets are successfully being applied to accounts in the org.    Would you check that you successfully applied the CFT to the log archive account and that the s3 bucket is setup to send the sns notifications to our sns topic.  
A description of how the service operates can be found here.
https://github.com/CrowdStrike/Cloud-AWS/tree/master/Discover-for-Cloud-Templates/AWS#how-crowdstrike-discover-works
Here is a script that you can use to query our API to check the configuration of your log archive account.  
https://github.com/CrowdStrike/Cloud-AWS/tree/master/Discover-for-Cloud-Templates/AWS/troubleshooting/scripts
(The script uses FalconPy) https://github.com/CrowdStrike/falconpy#installation--removal
python3 fd_accounts.py -f CLIENT_ID -s CLIENT_SECRET -c check -l
Example 
$ python3 fd_accounts.py -f CLIENT_ID -s CLIENT_SECRET -c check -l
Our support teams will also be able to assist you checking your configuration.

**Comment by syn7ack** [comment]
Awesome!  Thank you, @jhseceng!  I will run through these things, and let you know.  Appreciate the quick responses.

Also, just FYI, I do have a ticket out with CS Support, and was hoping to jump on a quick WebEx, but they just relayed me here.

**Comment by jhseceng** [comment]
Ok you can contact me at ***@***.*** if you are still having problems


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by syn7ack** [comment]
Good morning, @jhseceng.  I checked in our Master account, LogArchive account, and another account, and I am not able to find any SNS topics that match the format specified in that link you sent.  I'm also struggling to get FalconPy installed because of some "SSL: Certificate_Verify_Failed" errors from pip.

Your email address just came through as "***@***.***", so I am unable to reach out.  The ticket I've currently been working on with CS Support is 00517406.  Not sure if you are able to initiate contact through that?

**Comment by jhseceng** [comment]
Ok that makes sense.  You will need to load the log archive account cloudformation template that will set that up for you.   https://github.com/CrowdStrike/Cloud-AWS/blob/master/Control-Tower/documentation/implementation-guide.md#step-2-configuration-solution-to-deploy
Step 3.
Let me know if that works ok for you.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by syn7ack** [comment]
@jhseceng, so that was run back on 5/21 when I was initially setting this up.

I did find the configured S3 bucket notification that references that SNS topic, so it appears to have set everything up correctly.  Not sure why these environment changes are not reflecting, in that case.

**Comment by jhseceng** [comment]
Next check the IAM role is in place and the external ID. You can then ask via the support ticket that our support team check the settings for the log archive account.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by syn7ack** [comment]
The IAM role from the CloudFormation template does exist, and the external ID in that role matches the registered account info in the CS API.

New CS Case opened: 00526699

**Comment by jhseceng** [comment]
Ok thanks.  We will work with you via the case number

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jshcodes** [comment]
Closing as stale.
